# Generated by Django 2.2.13 on 2021-01-31 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ingrediente', models.CharField(max_length=200)),
                ('precio_ingrediente', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip_pedido', models.CharField(max_length=200)),
                ('precio_pedido', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_pedido', models.DateTimeField(verbose_name='fecha del Pedido')),
                ('porcentaje_oferta', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamano_sandwich', models.CharField(max_length=200)),
                ('precio_sandwich', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Sand_Ing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ingrediente')),
                ('tipo_sandwich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Sandwich')),
            ],
        ),
        migrations.CreateModel(
            name='Ped_Sand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Pedido')),
                ('tipo_sandwich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Sandwich')),
            ],
        ),
    ]
